package Vistax;
import Controller.ControlUniversal;
import Controller.VerificacionDeCredito;
import Modelos.Anticipo;
import Modelos.Socio;
import Utilerias.interfacex;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author root4142
 */
public class frmAnticipo extends javax.swing.JInternalFrame {
    private interfacex inter=new interfacex();
    private Vector<JTextField> txtCampos=new Vector<>();
    private Date date,date2;
    private Calendar c1 = new GregorianCalendar();
    private float limite=0;
    private boolean ins=true,b=false,c=false;
    private ControlUniversal control;
    private Anticipo anticipo;
    /**
     * Creates new form frmAnticipo
     */
    public frmAnticipo(ControlUniversal cont) {
        initComponents();
        control=cont;
        txtCampos.add(txtAnticipoID);
        txtCampos.add(txtSocioID);
        txtCampos.add(txtValor);
        anticipo=new Anticipo();
        date=new Date();
        date=control.getFechaSistemaSql();
        cboFecha.setDate(date);
        int auto = control.autoUniversal2("Anticipo","AnticipoID");
        txtAnticipoID.setText(String.valueOf(auto));
        txtSocioID.grabFocus();
    }
    private void Limpiar_Campos(){
        date=new Date();
        date=control.getFechaSistemaSql();
        cboFecha.setDate(date);
        for (JTextField o : txtCampos) {
            o.setText("");
        }
        txtObservacion.setText("Ninguna.");
        lblNombreSocio.setText("");
        lblSocioSueldo.setText("");
        ins=true;
        b=false;c=false;
        limite=0;
        int auto = control.autoUniversal2("Anticipo","AnticipoID");
        txtAnticipoID.setText(String.valueOf(auto));
        txtSocioID.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAnticipoID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSocioID = new javax.swing.JTextField();
        lblNombreSocio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboFecha = new com.toedter.calendar.JDateChooser();
        txtValor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblSocioSueldo = new javax.swing.JLabel();

        setTitle("Formulario de Anticipo para Socios.");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistax/Iconos/icon.jpeg"))); // NOI18N
        setName("frmAnticipo"); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("No. Anticipo :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtAnticipoID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAnticipoID.setEnabled(false);
        txtAnticipoID.setName("AnticipoID"); // NOI18N
        getContentPane().add(txtAnticipoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 130, -1));

        jLabel2.setText("Fecha :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        txtSocioID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSocioID.setName("SocioID"); // NOI18N
        txtSocioID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSocioIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtSocioID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 100, -1));

        lblNombreSocio.setBackground(java.awt.Color.white);
        lblNombreSocio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNombreSocio.setOpaque(true);
        getContentPane().add(lblNombreSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 260, 30));

        jLabel3.setText("ID Socio :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        cboFecha.setDateFormatString("MMMMM d, yyyy");
        cboFecha.setEnabled(false);
        getContentPane().add(cboFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, -1));

        txtValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor.setName("Valor"); // NOI18N
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 130, -1));

        jLabel4.setText("Observacion :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        txtObservacion.setColumns(20);
        txtObservacion.setRows(5);
        txtObservacion.setText("Ninguna.");
        txtObservacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtObservacionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtObservacion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, 120));

        jLabel5.setText("Valor :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 80, -1));

        jButton2.setText("Recuperar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 110, -1));

        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 100, -1));

        lblSocioSueldo.setBackground(java.awt.Color.white);
        lblSocioSueldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSocioSueldo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblSocioSueldo.setName(""); // NOI18N
        lblSocioSueldo.setOpaque(true);
        getContentPane().add(lblSocioSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, 30));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-594)/2, (screenSize.height-339)/2, 594, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void txtObservacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObservacionKeyTyped
        if(txtObservacion.getText().length()>=100){
            evt.consume();
        }
    }//GEN-LAST:event_txtObservacionKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int x = -1;
        try {
            x = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Ingrese No. del Anticipo : ", "Ingrese", JOptionPane.INFORMATION_MESSAGE));
            anticipo = new Anticipo();
            Object o[][] = control.seekUniversal(anticipo.getVectorData(), "Anticipo", x + "");
            if (o != null) {
                anticipo = new Anticipo(o);
                if (anticipo.getEstado().equals("D") || anticipo.getEstado().equals("N")) {
                    JOptionPane.showMessageDialog(rootPane, "No se Puede Mostrar Este anticipo Pues ya Esta Pagada o Anulado", "Mensaje", JOptionPane.ERROR_MESSAGE);
                } else {
                    txtAnticipoID.setText(anticipo.getAnticipoID() + "");
                    txtSocioID.setText(anticipo.getSocioID() + "");
                    txtSocioIDActionPerformed(evt);
                    cboFecha.setDate(inter.String_Date(anticipo.getFecha()));
                    txtValor.setText(inter.FormatoSimple(anticipo.getValor()));
                    txtSocioID.grabFocus();
                    ins = false;
                    b = false;
                    c = false;
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"Debe de ingresar un No. de Anticipo Valido","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean a=false, bb=false;
        for(JTextField o:txtCampos){
            if(o.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane,"Campo "+o.getName()+" se encuentra Vacio","Error",JOptionPane.ERROR_MESSAGE);
                o.grabFocus();
                a=false;
                break;
            }
            else{
                a=true;
            }
        }
        Date d=cboFecha.getDate();
        Calendar c2 = new GregorianCalendar();
        c2.setTime(d);
        if (a) {
            if (!b) {
                JOptionPane.showMessageDialog(rootPane, "Campo Socio ID no esta Validado", "Error", JOptionPane.ERROR_MESSAGE);
                bb = false;
                txtSocioID.grabFocus();
            }
            else if(txtObservacion.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane,"Campo Observacion se encuentra Vacio","Error",JOptionPane.ERROR_MESSAGE);
                txtObservacion.grabFocus();
                bb=false;
            }
            else if(inter.String_Float(txtValor.getText())>limite){
                JOptionPane.showMessageDialog(rootPane,"Anticipo mayor de lo permitido (15%)","Error",JOptionPane.ERROR_MESSAGE);
                txtValor.grabFocus();
                bb=false;
            }
            else if(!c1.before(c2)){
                JOptionPane.showMessageDialog(rootPane,"Anticipo Solo se otorga con una antiguedad mayor a los 30 dias","Error",JOptionPane.ERROR_MESSAGE);
                txtSocioID.grabFocus();
                bb=false;
            }
            else {
                bb = true;
            }
            if (bb) {
                String fecha = "", estado = "";
                fecha=inter.Date_String(d);
                estado = "G";
                anticipo=new Anticipo(inter.String_Int(txtAnticipoID.getText()),inter.String_Int(txtSocioID.getText()), fecha,inter.String_Float(txtValor.getText()), estado,txtObservacion.getText());
                if (ins) {
                    control.insUniversal(anticipo.getVectorData(), "Anticipo");
                } else {
                    control.updUniversal(anticipo.getVectorData(), "Anticipo", txtAnticipoID.getText());
                }
                Limpiar_Campos();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtSocioIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSocioIDActionPerformed
        Socio socio = new Socio();
        Object o[][] = control.seekUniversal(socio.getVectorData(), "Socio", txtSocioID.getText());
        if (o != null) {
            socio=new Socio(o);
            VerificacionDeCredito verifica=new VerificacionDeCredito(socio.getSocioID(),control);
            if(verifica.getTipoCredito()==1){
                JOptionPane.showMessageDialog(rootPane,"Ya hay un Anticipo Vigente no Cancelado por parte de este Socio","Error",JOptionPane.ERROR_MESSAGE);
                txtSocioID.grabFocus();
            }
            else if(verifica.getTipoCredito()==2){
                JOptionPane.showMessageDialog(rootPane,"Ya hay un Prestamo Vigente no Cancelado por parte de este Socio","Error",JOptionPane.ERROR_MESSAGE);
                txtSocioID.grabFocus();
            }
            else if (verifica.getTipoCredito() == 3) {
                JOptionPane.showMessageDialog(rootPane, "Ya hay una Factura Vigente no Cancelado por parte de este Socio", "Error", JOptionPane.ERROR_MESSAGE);
                txtSocioID.grabFocus();
            }
            else{
                lblNombreSocio.setText(socio.getNombre());
                lblSocioSueldo.setText(socio.getSueldo() + "");
                limite = (float) (socio.getSueldo() * 0.15);
                date2 = inter.String_Date(socio.getFechaIngreso());
                c1 = new GregorianCalendar();
                c1.setTime(date2);
                c1.add(Calendar.DAY_OF_MONTH, 30);
                b = true;
                txtValor.grabFocus();
            }
        }
    }//GEN-LAST:event_txtSocioIDActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser cboFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreSocio;
    private javax.swing.JLabel lblSocioSueldo;
    private javax.swing.JTextField txtAnticipoID;
    private javax.swing.JTextArea txtObservacion;
    private javax.swing.JTextField txtSocioID;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
