package Vistax;
import Controller.ControlUniversal;
import Modelos.Banco;
import Modelos.Cheque;
import Modelos.Cuenta;
import Modelos.Moneda;
import Utilerias.interfacex;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author root4142
 */
public class frmCheque extends javax.swing.JInternalFrame {
    private interfacex inter=new interfacex();
    private Vector<JTextField> txtCampos=new Vector<>();
    private Vector<JComboBox> cboCombos=new Vector<>();
    private Vector<JLabel> lblLabels=new Vector<>();
    DefaultComboBoxModel modelo=new DefaultComboBoxModel();
    private Date date;
    private boolean ins=true,b=false,c=false;
    private ControlUniversal control;
    private Cheque cheque;
    /**
     * Creates new form frmCheque
     */
    public frmCheque(ControlUniversal cont) {
        initComponents();
        control=cont;
        txtCampos.add(txtChequeID);
        txtCampos.add(txtBancoID);
        txtCampos.add(txtBeneficiario);
        txtCampos.add(txtValor);
        lblLabels.add(lblBancoNombre);
        lblLabels.add(lblCuentaNombre);
        lblLabels.add(lblCuentaMoneda);
        cboCombos.add(cboCuentaID);
        cboCombos.add(cboEstado);
        cheque=new Cheque();
        date=new Date();
        date=control.getFechaSistemaSql();
        cboFecha.setDate(date);
        modelo.addElement("Cuentas de Bancos");
        cboCuentaID.setModel(modelo);
        int auto = control.autoUniversal2("Cheque","ChequeID");
        txtChequeID.setText(String.valueOf(auto));
        txtBancoID.grabFocus();
    }
    private void Limpiar_Campos(){
        modelo=new DefaultComboBoxModel();
        modelo.addElement("Cuentas de Bancos");
        cboCuentaID.setModel(modelo);
        date=new Date();
        date=control.getFechaSistemaSql();
        cboFecha.setDate(date);
        for (JTextField o : txtCampos) {
            o.setText("");
        }
        cboEstado.setSelectedIndex(0);
        for(JLabel q:lblLabels){
            q.setText("Nombre del "+q.getName()+".");
        }
        ins=true;
        b=false;c=false;
        int auto = control.autoUniversal2("Cheque","ChequeID");
        txtChequeID.setText(String.valueOf(auto));
        txtBancoID.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtChequeID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBancoID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblCuentaMoneda = new javax.swing.JLabel();
        lblBancoNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox();
        cboCuentaID = new javax.swing.JComboBox();
        cboFecha = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        lblCuentaNombre = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBeneficiario = new javax.swing.JTextField();

        setTitle("Formulario de Cheque Bancario.");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistax/Iconos/icon.jpeg"))); // NOI18N
        setName("frmCheque"); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cuenta :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txtValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor.setName("Valor"); // NOI18N
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 130, -1));

        jLabel2.setText("ID Cheque :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        txtChequeID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtChequeID.setEnabled(false);
        txtChequeID.setName("ChequeID"); // NOI18N
        getContentPane().add(txtChequeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 190, -1));

        jLabel4.setText("Valor :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel7.setText("ID Banco :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtBancoID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBancoID.setName("BancoID"); // NOI18N
        txtBancoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBancoIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtBancoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 70, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 80, -1));

        jButton2.setText("Recuperar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 110, -1));

        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 100, -1));

        lblCuentaMoneda.setBackground(java.awt.Color.white);
        lblCuentaMoneda.setText("Nombre de la Moneda.");
        lblCuentaMoneda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblCuentaMoneda.setName("Moneda"); // NOI18N
        lblCuentaMoneda.setOpaque(true);
        getContentPane().add(lblCuentaMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 230, 30));

        lblBancoNombre.setBackground(java.awt.Color.white);
        lblBancoNombre.setText("Nombre del Banco.");
        lblBancoNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblBancoNombre.setName("Banco"); // NOI18N
        lblBancoNombre.setOpaque(true);
        getContentPane().add(lblBancoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 67, 250, 30));

        jLabel3.setText("Estado :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel5.setText("Nombre del Beneficiario :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gravado", "Procesado", "Anulado" }));
        cboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(cboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 130, -1));

        cboCuentaID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cuentas de Bancos" }));
        cboCuentaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCuentaIDActionPerformed(evt);
            }
        });
        getContentPane().add(cboCuentaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 190, -1));

        cboFecha.setDateFormatString("MMMMM d, yyyy");
        getContentPane().add(cboFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 190, -1));

        txtObservacion.setColumns(100);
        txtObservacion.setLineWrap(true);
        txtObservacion.setRows(5);
        txtObservacion.setText("Ninguna.");
        txtObservacion.setWrapStyleWord(true);
        txtObservacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Observacion.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        txtObservacion.setName("Observacion."); // NOI18N
        txtObservacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtObservacionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtObservacion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 310, -1));

        lblCuentaNombre.setBackground(java.awt.Color.white);
        lblCuentaNombre.setText("Nombre de la Cuenta.");
        lblCuentaNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblCuentaNombre.setName("Cuenta"); // NOI18N
        lblCuentaNombre.setOpaque(true);
        getContentPane().add(lblCuentaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 230, 30));

        jLabel6.setText("Fecha :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txtBeneficiario.setColumns(50);
        txtBeneficiario.setName("Beneficiario"); // NOI18N
        txtBeneficiario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBeneficiarioKeyTyped(evt);
            }
        });
        getContentPane().add(txtBeneficiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 310, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-601)/2, (screenSize.height-472)/2, 601, 472);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBancoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBancoIDActionPerformed
        Banco banco = new Banco();
        Object o[][] = control.seekUniversal(banco.getVectorData(), "Banco", txtBancoID.getText());
        if (o != null) {
            banco=new Banco(o);
            lblBancoNombre.setText(banco.getNombre_Banco());
            modelo=control.getModelo("Cuenta","BancoID","CuentaID",txtBancoID.getText());
            cboCuentaID.setModel(modelo);
            cboCuentaID.grabFocus();
            b=true;
        }
    }//GEN-LAST:event_txtBancoIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int x = -1;
        try {
            x = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Ingrese No. del Cheque : ", "Ingrese", JOptionPane.INFORMATION_MESSAGE));
            cheque = new Cheque();
            Object o[][] = control.seekUniversal(cheque.getVectorData(), "Cheque", x + "");
            if (o != null) {
                cheque = new Cheque(o);
                if (cheque.getEstado().equals("P") || cheque.getEstado().equals("N")) {
                    JOptionPane.showMessageDialog(rootPane, "No se Puede Mostrar Este Cheque Pues ya Esta Pagada o Anulado", "Mensaje", JOptionPane.ERROR_MESSAGE);
                } else {
                    txtChequeID.setText(cheque.getChequeID() + "");
                    txtBancoID.setText(cheque.getBancoID() + "");
                    txtBancoIDActionPerformed(evt);
                    cboCuentaID.setSelectedItem(inter.String_Object(cheque.getCuentaID()));
                    cboCuentaIDActionPerformed(evt);
                    cboFecha.setDate(inter.String_Date(cheque.getFecha()));
                    txtBeneficiario.setText(cheque.getBeneficiario());
                    txtValor.setText(inter.FormatoSimple(cheque.getValor()));
                    if (cheque.getEstado().equals("G")) {
                        cboCombos.get(1).setSelectedIndex(0);
                    } else if (cheque.getEstado().equals("P")) {
                        cboCombos.get(1).setSelectedIndex(1);
                    } else if (cheque.getEstado().equals("A")) {
                        cboCombos.get(1).setSelectedIndex(2);
                    }
                    txtBancoID.grabFocus();
                    ins = false;
                    b = false;
                    c = false;
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"Debe de ingresar un No. de Cheque Valido","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean a=false, bb=false;
        for(JTextField o:txtCampos){
            if(o.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane,"Campo "+o.getName()+" se encuentra Vacio","Error",JOptionPane.ERROR_MESSAGE);
                o.grabFocus();
                a=false;
                break;
            }
            else{
                a=true;
            }
        }
        if (a) {
            if (!b) {
                JOptionPane.showMessageDialog(rootPane, "Campo Banco ID no esta Validado", "Error", JOptionPane.ERROR_MESSAGE);
                bb = false;
                txtBancoID.grabFocus();
            }
            else if (!c) {
                JOptionPane.showMessageDialog(rootPane, "Se debe de seleccionar una Cuenta de la lista desplegable", "Error", JOptionPane.ERROR_MESSAGE);
                bb = false;
                cboCuentaID.grabFocus();
            }
            else if(txtObservacion.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane,"Campo Observacion se encuentra Vacio","Error",JOptionPane.ERROR_MESSAGE);
                txtObservacion.grabFocus();
                bb=false;
            }
            else {
                bb = true;
            }
            if (bb) {
                String xx = "", yy = "";
                Date d=cboFecha.getDate();
                xx=inter.Date_String(d);
                if (cboEstado.getSelectedIndex() == 0) {
                    yy = "G";
                } else if (cboEstado.getSelectedIndex() == 1) {
                    yy = "P";
                }
                else if (cboEstado.getSelectedIndex() == 2) {
                    yy = "A";
                }
                cheque = new Cheque(inter.String_Int(txtChequeID.getText()), inter.String_Int(txtBancoID.getText()),cboCuentaID.getSelectedItem().toString(),xx,txtBeneficiario.getText().toUpperCase(),inter.String_Float(txtValor.getText()),yy,txtObservacion.getText().toUpperCase());
                if (ins) {
                    control.insUniversal(cheque.getVectorData(), "Cheque");
                } else {
                    control.updUniversal(cheque.getVectorData(), "Cheque", txtChequeID.getText());
                }
                Limpiar_Campos();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadoActionPerformed
        txtObservacion.grabFocus();
    }//GEN-LAST:event_cboEstadoActionPerformed

    private void cboCuentaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCuentaIDActionPerformed
        Cuenta cuenta = new Cuenta();
        Object o[][] = control.seekUniversal(cuenta.getVectorData(), "Cuenta","'"+cboCuentaID.getSelectedItem().toString()+"'");
        if (o != null) {
            cuenta=new Cuenta(o);
            lblCuentaNombre.setText(cuenta.getNombre());
            Moneda moneda = new Moneda();
            Object oo[][] = control.seekUniversal(moneda.getVectorData(), "Moneda",cuenta.getMonedaID()+"");
            if (oo != null) {
                moneda = new Moneda(oo);
                lblCuentaMoneda.setText(moneda.getNombre());
            }
            c=true;
            cboFecha.grabFocus();
        }
    }//GEN-LAST:event_cboCuentaIDActionPerformed

    private void txtBeneficiarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBeneficiarioKeyTyped
        if(txtBeneficiario.getText().length()>=50){
            evt.consume();
        }
    }//GEN-LAST:event_txtBeneficiarioKeyTyped

    private void txtObservacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObservacionKeyTyped
        if(txtObservacion.getText().length()>=100){
            evt.consume();
        }
    }//GEN-LAST:event_txtObservacionKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboCuentaID;
    private javax.swing.JComboBox cboEstado;
    private com.toedter.calendar.JDateChooser cboFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBancoNombre;
    private javax.swing.JLabel lblCuentaMoneda;
    private javax.swing.JLabel lblCuentaNombre;
    private javax.swing.JTextField txtBancoID;
    private javax.swing.JTextField txtBeneficiario;
    private javax.swing.JTextField txtChequeID;
    private javax.swing.JTextArea txtObservacion;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
