package Vistax;
import Controller.ControlUniversal;
import Modelos.Articulo;
import Modelos.Bodega;
import Modelos.CompraCab;
import Modelos.CompraDet;
import Modelos.Proveedor;
import Utilerias.interfacex;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author root4142
 */
public class frmCompraUdp extends javax.swing.JInternalFrame {
    private interfacex inter=new interfacex();
    private Vector<JTextField> txtCampos=new Vector<>();
    private Vector<JLabel> lblLabels=new Vector<>();
    private Vector<JComboBox> cboCombos=new Vector<>();
    private Vector<CompraDet> CompraDet=new Vector<>();
    private Vector titulos,data=new Vector();
    private DefaultTableModel modelo;
    private boolean ins=false,b=false,c=false;
    private Date date;
    private float totalBruto=0,total=0,limite=0;
    private ControlUniversal control;
    private CompraCab compracab;
    private CompraDet compradet;
    /**
     * Creates new form frmCompraUdp
     */
    public frmCompraUdp(ControlUniversal cont) {
        control=cont;
        titulos=new Vector();
        titulos.addElement("ID Articulo");titulos.addElement("Nombre del Articulo");titulos.addElement("Cantidad");
        titulos.addElement("Precio unitario");titulos.addElement("ISV");titulos.addElement("Total");
        initComponents();
        txtCampos.add(txtProveedorID);
        txtCampos.add(txtBodegaID);
        txtCampos.add(txtFacturaID);
        lblLabels.add(txtCompraID);
        lblLabels.add(lblNombreProveedor);
        lblLabels.add(lblNombreBodega);
        lblLabels.add(lblDireccionProveedor);
        cboCombos.add(cboEstado);
        cboCombos.add(cboTipo);
        modelo=(DefaultTableModel) Tabla.getModel();
        Tabla.setModel(modelo);
        compracab=new CompraCab();
        date=new Date();
        date=control.getFechaSistemaSql();
        cboFecha.setDate(date);
        txtProveedorID.grabFocus();
    }
    private void Limpiar_Campos(){
        for (JTextField o : txtCampos) {
            o.setText("");
        }
        for (JLabel o : lblLabels) {
            o.setText("");
        }
        for(JComboBox p: cboCombos){
            p.setSelectedIndex(0);
        }
        date=new Date();
        date=control.getFechaSistemaSql();
        cboFecha.setDate(date);
        cboTipo.setSelectedIndex(0);
        ins=false;
        b=false;c=false;
        total=0;limite=0;totalBruto=0;
        txtProveedorID.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBodegaID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtProveedorID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFacturaID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox();
        lblDireccionProveedor = new javax.swing.JLabel();
        lblNombreBodega = new javax.swing.JLabel();
        lblNombreProveedor = new javax.swing.JLabel();
        valid = new javax.swing.JButton();
        cboFecha = new com.toedter.calendar.JDateChooser();
        cboEstado = new javax.swing.JComboBox();
        txtCompraID = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtArticuloID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        chkISV = new javax.swing.JCheckBox();
        lblPrecio = new javax.swing.JLabel();
        lblNombreArticulo = new javax.swing.JLabel();
        lblISV = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnQuitarLinea = new javax.swing.JButton();
        btnAgregarLinea = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setTitle("Formulario de Actualizacion de Estado de las Compras.");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistax/Iconos/icon.jpeg"))); // NOI18N
        setName("frmCompraUdp"); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Encabezado de la Compra."));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBodegaID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBodegaID.setName("BodegaID"); // NOI18N
        txtBodegaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBodegaIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtBodegaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("No. de Compra :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Codigo de Proveedor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtProveedorID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtProveedorID.setName("ProveedorID"); // NOI18N
        txtProveedorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProveedorIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtProveedorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Codigo de Bodega");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("No. Factura del Proveedor");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        txtFacturaID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFacturaID.setName("FacturaID"); // NOI18N
        jPanel1.add(txtFacturaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Nombre de Proveedor");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nombre de Bodega");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Dirección de Proveedor");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Año-Mes-Día");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Tipo de la Compra");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Estado de la Compra");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Contado", "Credito" }));
        jPanel1.add(cboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 160, -1));

        lblDireccionProveedor.setBackground(java.awt.Color.white);
        lblDireccionProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDireccionProveedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblDireccionProveedor.setName("Estado"); // NOI18N
        lblDireccionProveedor.setOpaque(true);
        jPanel1.add(lblDireccionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 270, 30));

        lblNombreBodega.setBackground(java.awt.Color.white);
        lblNombreBodega.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreBodega.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNombreBodega.setName("Estado"); // NOI18N
        lblNombreBodega.setOpaque(true);
        jPanel1.add(lblNombreBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 270, 30));

        lblNombreProveedor.setBackground(java.awt.Color.white);
        lblNombreProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreProveedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNombreProveedor.setName("Estado"); // NOI18N
        lblNombreProveedor.setOpaque(true);
        jPanel1.add(lblNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 270, 30));

        valid.setText("Validadar");
        valid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validActionPerformed(evt);
            }
        });
        jPanel1.add(valid, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 130, -1));

        cboFecha.setDateFormatString("MMMMM d, yyyy");
        jPanel1.add(cboFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 190, -1));

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grabado", "Procesado", "Anulado" }));
        jPanel1.add(cboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 150, -1));

        txtCompraID.setBackground(java.awt.Color.white);
        txtCompraID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtCompraID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCompraID.setName("CompraID"); // NOI18N
        txtCompraID.setOpaque(true);
        jPanel1.add(txtCompraID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 110, 25));

        jButton4.setText("Recuperar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, 240));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de la Compra."));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtArticuloID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtArticuloID.setName("ArticuloID"); // NOI18N
        txtArticuloID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArticuloIDActionPerformed(evt);
            }
        });
        jPanel2.add(txtArticuloID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Codigo de Articulo");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Nombre del Articulo");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad.setName("Cantidad"); // NOI18N
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        jPanel2.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Cantidad");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Precio");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Total a Pagar :");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("ISV");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        chkISV.setText("ISV");
        chkISV.setEnabled(false);
        jPanel2.add(chkISV, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        lblPrecio.setBackground(java.awt.Color.white);
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrecio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblPrecio.setOpaque(true);
        jPanel2.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 110, 30));

        lblNombreArticulo.setBackground(java.awt.Color.white);
        lblNombreArticulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNombreArticulo.setOpaque(true);
        jPanel2.add(lblNombreArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 240, 30));

        lblISV.setBackground(java.awt.Color.white);
        lblISV.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblISV.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblISV.setOpaque(true);
        jPanel2.add(lblISV, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 110, 30));

        lblTotal.setBackground(java.awt.Color.white);
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblTotal.setOpaque(true);
        jPanel2.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 110, 30));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(data,titulos)
            {
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            }
        );
        jScrollPane1.setViewportView(Tabla);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 860, 160));

        btnQuitarLinea.setText("Quitar Linea");
        btnQuitarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarLineaActionPerformed(evt);
            }
        });
        jPanel2.add(btnQuitarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 150, -1));

        btnAgregarLinea.setText("Agregar Linea");
        btnAgregarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLineaActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 150, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 890, 340));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 100, 50));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 100, 50));

        jButton3.setText("Procesar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 100, 50));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-925)/2, (screenSize.height-643)/2, 925, 643);
    }// </editor-fold>//GEN-END:initComponents

    private void validBodegaID(){
        Bodega bodega = new Bodega();
        Object o[][] = control.seekUniversal(bodega.getVectorData(), "Bodega", txtBodegaID.getText());
        if (o != null) {
            bodega=new Bodega(o);
            lblNombreBodega.setText(bodega.getNombre());
            c=true;
            txtFacturaID.grabFocus();
        }
    }
    
    private void txtBodegaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBodegaIDActionPerformed
        validBodegaID();
    }//GEN-LAST:event_txtBodegaIDActionPerformed

    private void validProveedorID(){
        Proveedor proveedor = new Proveedor();
        Object o[][] = control.seekUniversal(proveedor.getVectorData(), "Proveedor", txtProveedorID.getText());
        if (o != null) {
            proveedor=new Proveedor(o);
            lblNombreProveedor.setText(proveedor.getNombre());
            lblDireccionProveedor.setText(proveedor.getDireccion());
            limite=proveedor.getLimite();
            b=true;
            txtBodegaID.grabFocus();
        }
    }
    
    private void txtProveedorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProveedorIDActionPerformed
        validProveedorID();
    }//GEN-LAST:event_txtProveedorIDActionPerformed

    private void validActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validActionPerformed
        boolean aa=false;
        for(JTextField o:txtCampos){
            if (o.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Campo " + o.getName() + " se encuentra Vacio", "Error", JOptionPane.ERROR_MESSAGE);
                o.grabFocus();
                aa = false;
                break;
            } else {
                aa = true;
            }
        }
        if (aa) {
            if (!b) {
                JOptionPane.showMessageDialog(rootPane, "Campo Codigo de Proveedor no esta validado", "Error", JOptionPane.ERROR_MESSAGE);
                txtProveedorID.grabFocus();
            } else if (!c) {
                JOptionPane.showMessageDialog(rootPane, "Campo Codigo de la Bodega no esta validado", "Error", JOptionPane.ERROR_MESSAGE);
                txtBodegaID.grabFocus();
            } else {
                String d = "",dd="";
                if (cboTipo.getSelectedIndex() == 0) {
                    d = "X";
                } else {
                    d = "Y";
                }
                if (cboEstado.getSelectedIndex() == 0) {
                    dd = "G";
                } else if (cboEstado.getSelectedIndex() == 1) {
                    dd = "P";
                }else if (cboEstado.getSelectedIndex() == 2) {
                    dd = "A";
                }
                String xx = "";
                Date dat = cboFecha.getDate();
                xx = inter.Date_String(dat);
                compracab = new CompraCab(inter.String_Int(txtCompraID.getText()), inter.String_Int(txtProveedorID.getText()), inter.String_Int(txtBodegaID.getText()), xx, inter.String_Int(txtFacturaID.getText()), dd, d);
                ins = true;
                txtArticuloID.grabFocus();
            }
        }
    }//GEN-LAST:event_validActionPerformed

    private void txtArticuloIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArticuloIDActionPerformed
        if (ins) {
            if (!txtArticuloID.getText().isEmpty()) {
                Articulo articulo = new Articulo();
                Object o[][] = control.seekUniversal(articulo.getVectorData(), "Articulo", txtArticuloID.getText());
                if (o != null) {
                    articulo = new Articulo(o);
                    lblNombreArticulo.setText(articulo.getNombre());
                    lblPrecio.setText(articulo.getPrecio() + "");
                    if (articulo.getISV() == 1) {
                        chkISV.setSelected(true);
                    } else {
                        chkISV.setSelected(false);
                    }
                    txtCantidad.grabFocus();
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane,"El Campo Articulo ID esta Vacio","Error",JOptionPane.ERROR_MESSAGE);
                txtArticuloID.grabFocus();
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"El encabezado de la Compra no esta validado aun!!!","Error",JOptionPane.ERROR_MESSAGE);
            valid.grabFocus();
        }
    }//GEN-LAST:event_txtArticuloIDActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        int cc=inter.String_Int(txtCantidad.getText());
        if (!txtArticuloID.getText().isEmpty()) {
            float aa = inter.String_Float(lblPrecio.getText());
            if (chkISV.isSelected()) {
                float z = (float) (cc * aa * 0.12);
                lblISV.setText(z + "");
                totalBruto = (float) ((cc * aa) + z);
            } else {
                lblISV.setText("0");
                totalBruto = (float) ((cc * aa) + 0);
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Campo Codigo de Articulo se encuentra vacio","Error",JOptionPane.ERROR_MESSAGE);
            txtArticuloID.grabFocus();
        }
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnQuitarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarLineaActionPerformed
        int x=-1;
        x=Tabla.getSelectedRow();
        if(x<0){
            JOptionPane.showMessageDialog(rootPane, "No se puede debes de seleccionar una linea de la tabla");
        }
        else{
            total=total- Float.valueOf(modelo.getValueAt(x, 5).toString());
            lblTotal.setText(total+"");
            CompraDet.remove(x);
            modelo.removeRow(x);
            txtArticuloID.setText("");txtBodegaID.setText("");txtCantidad.setText("");
            lblNombreArticulo.setText("");
//            lblDireccionProveedor.setText("");
//            lblNombreBodega.setText("");
            lblPrecio.setText("");lblISV.setText("");chkISV.setSelected(false);
            txtArticuloID.grabFocus();
        }
    }//GEN-LAST:event_btnQuitarLineaActionPerformed

    private void btnAgregarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLineaActionPerformed
        if((txtArticuloID.getText().isEmpty()) || (txtCantidad.getText().isEmpty())){
            JOptionPane.showMessageDialog(rootPane, "No se puede ingresar linea con campos vacios");
        }
        else{
            float temp=total+totalBruto;
            if (temp <= limite) {
                Vector rou = new Vector();
                rou.addElement(txtArticuloID.getText().toUpperCase());
                rou.addElement(lblNombreArticulo.getText().toUpperCase());
                rou.addElement(txtCantidad.getText());
                rou.addElement(lblPrecio.getText());
                rou.addElement(lblISV.getText());
                rou.addElement(totalBruto);
                total = total + totalBruto;
                lblTotal.setText(total + "");
                int c1 = -1, c2 = -1, c3 = -1, c4 = -1;
                float f1 = 0, f2 = 0;
                c1 = inter.String_Int(txtCompraID.getText());
                c2 = inter.String_Int(txtArticuloID.getText());
                c3 = Integer.valueOf(txtCantidad.getText());
                f1 = inter.String_Float(lblPrecio.getText());
                if (chkISV.isSelected()) {
                    c4 = 1;
                } else {
                    c4 = 0;
                }
                compradet = new CompraDet(c1, c2, c3, f1, c4);
                CompraDet.addElement(compradet);
                modelo.addRow(rou);
            }
            else{
                float ca=limite-temp;
                JOptionPane.showMessageDialog(rootPane,"No se puede agregar linea por que se excede\n limite con el proveedor por cantidad de "+ca);
            }
            totalBruto = 0;
            txtArticuloID.setText("");
            txtCantidad.setText("");
            lblNombreArticulo.setText("");
            lblPrecio.setText("");
            lblISV.setText("");
            chkISV.setSelected(false);
            txtArticuloID.grabFocus();
        }
    }//GEN-LAST:event_btnAgregarLineaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Limpiar_Campos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(!ins){
            JOptionPane.showMessageDialog(rootPane,"El encabezado de la Compra no esta validado aun!!!","Error",JOptionPane.ERROR_MESSAGE);
            valid.grabFocus();
        }
        else if(modelo.getRowCount()==0){
            JOptionPane.showMessageDialog(rootPane, "No se han ingresado Articulos en el detalle de la factura");
            txtArticuloID.grabFocus();
        }
        else{
            int res=JOptionPane.showConfirmDialog(rootPane,"¿Desea ACTUALIZAR ESTA FACTURA?","PREGUNTA",JOptionPane.YES_NO_OPTION);
            if(res==JOptionPane.YES_OPTION){
                boolean y=control.updUniversal2(compracab.getVectorData(), "CompraCab",txtCompraID.getText());
                boolean x=false;
                x=control.delUniversal2("CompraDet","CompraID="+txtCompraID.getText());
                if (!x) {
                    JOptionPane.showMessageDialog(rootPane, "Proceso de Actualizacion Fallo en Borrado de Detalle");
                }
                for(CompraDet o:CompraDet){
                    x=control.insUniversal2(o.getVectorData(), "CompraDet");
                    if(!x){
                        JOptionPane.showMessageDialog(rootPane, "Proceso de Actualizacion Fallo en Insercion de Detalle");
                        break;
                    }
                }
                if((y) && (x)){
                    JOptionPane.showMessageDialog(rootPane, "FACTURA ACTUALIZADA CON EXITO");
                }
                totalBruto = 0;
                txtArticuloID.setText("");
                txtCantidad.setText("");
                lblNombreArticulo.setText("");
                lblPrecio.setText("");
                lblISV.setText("");
                chkISV.setSelected(false);
                CompraDet.clear();
                for(int e=modelo.getRowCount()-1;e>-1;e--){
                    modelo.removeRow(e);
                }
                Limpiar_Campos();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int x=-1;
        try{
            x = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Ingrese No. de la Factura : ", "Ingrese", JOptionPane.INFORMATION_MESSAGE));
            compracab = new CompraCab();
            Object o[][] = control.seekUniversal(compracab.getVectorData(), "CompraCab", x+"" );
            if (o != null) {
                compracab = new CompraCab(o);
                if (compracab.getEstado().equals("P")) {
                    JOptionPane.showMessageDialog(rootPane,"No se Puede Mostrar Esta Orden de Compra Pues ya Esta Pagada","Mensaje",JOptionPane.ERROR_MESSAGE);
                }
                else {
                    txtCompraID.setText(compracab.getCompraID() + "");
                    cboFecha.setDate(inter.String_Date(compracab.getFecha()));
                    txtProveedorID.setText(compracab.getProveedorID() + "");
                    validProveedorID();
                    txtBodegaID.setText(compracab.getBodegaID() + "");
                    txtBodegaIDActionPerformed(evt);
                    txtFacturaID.setText(compracab.getFactura() + "");
                    if (compracab.getEstado().equals("G")) {
                        cboCombos.get(0).setSelectedIndex(0);
                    } else if (compracab.getEstado().equals("P")) {
                        cboCombos.get(0).setSelectedIndex(1);
                    } else if (compracab.getEstado().equals("N")) {
                        cboCombos.get(0).setSelectedIndex(2);
                    }
                    if (compracab.getTipo().equals("X")) {
                        cboCombos.get(1).setSelectedIndex(0);
                    } else if (compracab.getTipo().equals("Y")) {
                        cboCombos.get(1).setSelectedIndex(1);
                    }
                    validActionPerformed(evt);

                    compradet = new CompraDet();
                    Vector<Object[][]> kk = control.seekUniversalVector(compradet.getVectorData(), "CompraDet", x + "");
                    if (!kk.isEmpty()) {
                        for (Object ll[][] : kk) {
                            compradet = new CompraDet(ll);
                            txtArticuloID.setText(compradet.getArticuloID() + "");
                            txtArticuloIDActionPerformed(evt);
                            txtCantidad.setText(compradet.getCantidad() + "");
                            txtCantidadActionPerformed(evt);
                            btnAgregarLineaActionPerformed(evt);
                        }
                    }

                    ins = false;
                    b = false;
                    c = false;
                    txtProveedorID.grabFocus();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Debe de ingresar un No. de Factura Valido","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnAgregarLinea;
    private javax.swing.JButton btnQuitarLinea;
    private javax.swing.JComboBox cboEstado;
    private com.toedter.calendar.JDateChooser cboFecha;
    private javax.swing.JComboBox cboTipo;
    private javax.swing.JCheckBox chkISV;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDireccionProveedor;
    private javax.swing.JLabel lblISV;
    private javax.swing.JLabel lblNombreArticulo;
    private javax.swing.JLabel lblNombreBodega;
    private javax.swing.JLabel lblNombreProveedor;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtArticuloID;
    private javax.swing.JTextField txtBodegaID;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JLabel txtCompraID;
    private javax.swing.JTextField txtFacturaID;
    private javax.swing.JTextField txtProveedorID;
    private javax.swing.JButton valid;
    // End of variables declaration//GEN-END:variables
}
