package Vistax;
import Controller.ControlUniversal;
import Modelos.CompraCab;
import Modelos.Proveedor;
import Modelos.Banco;
import Modelos.Cheque;
import Modelos.CompraDet;
import Modelos.Cuenta;
import Modelos.PagoCab;
import Modelos.PagoDet;
import Utilerias.interfacex;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author root4142
 */
public class frmPago extends javax.swing.JInternalFrame {
    private interfacex inter=new interfacex();
    private Vector<JTextField> txtCampos=new Vector<>();
    private Vector<JLabel> lblLabels=new Vector<>();
    private Vector<PagoDet> PagoDet=new Vector<>();
    private Vector titulos,data=new Vector();
    DefaultTableModel modelo;
    DefaultComboBoxModel modelo1=new DefaultComboBoxModel();
    private boolean ins=false,a=false,b=false,c=false,d=false;
    private float totalBruto=0,total=0,limite=0;
    private ControlUniversal control;
    private PagoCab pagocab;
    private PagoDet pagodet;
    
    public frmPago(ControlUniversal cont) {
        control=cont;
        titulos=new Vector();
        titulos.addElement("No. de Compra");titulos.addElement("No. de Factura del Proveedor");titulos.addElement("SubTotal");
        initComponents();
        txtCampos.add(txtPagoID);
        txtCampos.add(txtFecha);
        txtCampos.add(txtProveedorID);
        txtCampos.add(txtChequeID);
        lblLabels.add(lblNombreProveedor);
        lblLabels.add(lblDireccionProveedor);
        lblLabels.add(lblBancoNombre);
        lblLabels.add(lblCuentaID);
        lblLabels.add(lblCuentaNombre);
        lblLabels.add(lblNombreBeneficiario);
        lblLabels.add(lblValor);
        lblLabels.add(lblEstado);
        modelo=(DefaultTableModel) Tabla.getModel();
        Tabla.setModel(modelo);
        pagocab=new PagoCab();
        txtFecha.setText(control.getFechaSistema());
        lblEstado.setText("PROCESADA");
        int auto = control.autoUniversal2("PagoCab","PagoID");
        txtPagoID.setText(String.valueOf(auto));
        txtProveedorID.grabFocus();
    }
    private void Limpiar_Campos(){
        for (JTextField o : txtCampos) {
            o.setText("");
        }
        for (JLabel o : lblLabels) {
            o.setText("");
        }
        txtFecha.setText(control.getFechaSistema());
        lblEstado.setText("GRABADA");
        ins=false;
        a=false;b=false;c=false;d=false;
        total=0;limite=0;totalBruto=0;
        txtFecha.setText(control.getFechaSistema());
        lblEstado.setText("PROCESADA");
        int auto = control.autoUniversal2("PagoCab","PagoID");
        txtPagoID.setText(String.valueOf(auto));
        txtProveedorID.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtChequeID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPagoID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtProveedorID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblDireccionProveedor = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblNombreBeneficiario = new javax.swing.JLabel();
        lblNombreProveedor = new javax.swing.JLabel();
        valid = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblCuentaID = new javax.swing.JLabel();
        lblCuentaNombre = new javax.swing.JLabel();
        lblBancoNombre = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtCompraID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblFacturaID = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnQuitarLinea = new javax.swing.JButton();
        btnAgregarLinea = new javax.swing.JButton();

        setTitle("Formulario de Pago.");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistax/Iconos/icon.jpeg"))); // NOI18N
        setName("frmPago"); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Encabezado de Pago."));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtChequeID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtChequeID.setName("ChequeID"); // NOI18N
        txtChequeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChequeIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtChequeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("No. de Pago :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtPagoID.setBackground(java.awt.Color.white);
        txtPagoID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPagoID.setEnabled(false);
        txtPagoID.setName("CompraID"); // NOI18N
        jPanel1.add(txtPagoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Codigo de Proveedor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtProveedorID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtProveedorID.setName("ProveedorID"); // NOI18N
        txtProveedorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProveedorIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtProveedorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("No. de Cheque");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Nombre de Proveedor");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Beneficiario de Cheque");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Dirección de Proveedor");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Año-Mes-Día");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setEnabled(false);
        txtFecha.setName("Fecha"); // NOI18N
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 150, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Estado del Pago");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, -1));

        lblDireccionProveedor.setBackground(java.awt.Color.white);
        lblDireccionProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDireccionProveedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblDireccionProveedor.setName("Estado"); // NOI18N
        lblDireccionProveedor.setOpaque(true);
        jPanel1.add(lblDireccionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 270, 30));

        lblEstado.setBackground(java.awt.Color.white);
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado.setText("GRABADA");
        lblEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblEstado.setName("Estado"); // NOI18N
        lblEstado.setOpaque(true);
        jPanel1.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 130, 30));

        lblNombreBeneficiario.setBackground(java.awt.Color.white);
        lblNombreBeneficiario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreBeneficiario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNombreBeneficiario.setName("Beneficiario"); // NOI18N
        lblNombreBeneficiario.setOpaque(true);
        jPanel1.add(lblNombreBeneficiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 270, 30));

        lblNombreProveedor.setBackground(java.awt.Color.white);
        lblNombreProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreProveedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNombreProveedor.setName("Estado"); // NOI18N
        lblNombreProveedor.setOpaque(true);
        jPanel1.add(lblNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 270, 30));

        valid.setText("Validadar");
        valid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validActionPerformed(evt);
            }
        });
        jPanel1.add(valid, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 130, -1));

        jLabel2.setText("Cuenta :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel12.setText("Nombre del Banco :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lblCuentaID.setBackground(java.awt.Color.white);
        lblCuentaID.setText("Nombre del Banco.");
        lblCuentaID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblCuentaID.setName("Banco"); // NOI18N
        lblCuentaID.setOpaque(true);
        jPanel1.add(lblCuentaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 220, 30));

        lblCuentaNombre.setBackground(java.awt.Color.white);
        lblCuentaNombre.setText("Nombre de la Cuenta.");
        lblCuentaNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblCuentaNombre.setName("Cuenta"); // NOI18N
        lblCuentaNombre.setOpaque(true);
        jPanel1.add(lblCuentaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 230, 30));

        lblBancoNombre.setBackground(java.awt.Color.white);
        lblBancoNombre.setText("Nombre del Banco.");
        lblBancoNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblBancoNombre.setName("Banco"); // NOI18N
        lblBancoNombre.setOpaque(true);
        jPanel1.add(lblBancoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 250, 30));

        lblValor.setBackground(java.awt.Color.white);
        lblValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblValor.setName("Valor"); // NOI18N
        lblValor.setOpaque(true);
        jPanel1.add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, 280));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 100, 50));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 100, 50));

        jButton3.setText("Grabar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 100, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de Pago."));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCompraID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCompraID.setName("CompraID"); // NOI18N
        txtCompraID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompraIDActionPerformed(evt);
            }
        });
        jPanel2.add(txtCompraID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("No. de Compra");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("No. de Factura del Proveedor");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("SubTotal");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Total a Pagar :");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        lblSubtotal.setBackground(java.awt.Color.white);
        lblSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubtotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblSubtotal.setName("Subtotal"); // NOI18N
        lblSubtotal.setOpaque(true);
        jPanel2.add(lblSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 110, 30));

        lblFacturaID.setBackground(java.awt.Color.white);
        lblFacturaID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFacturaID.setName("FacturaID"); // NOI18N
        lblFacturaID.setOpaque(true);
        jPanel2.add(lblFacturaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 240, 30));

        lblTotal.setBackground(java.awt.Color.white);
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblTotal.setOpaque(true);
        jPanel2.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 110, 30));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(data,titulos)
            {
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            }
        );
        jScrollPane1.setViewportView(Tabla);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 860, 150));

        btnQuitarLinea.setText("Quitar Linea");
        btnQuitarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarLineaActionPerformed(evt);
            }
        });
        jPanel2.add(btnQuitarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 150, -1));

        btnAgregarLinea.setText("Agregar Linea");
        btnAgregarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLineaActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 150, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 890, 290));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-924)/2, (screenSize.height-633)/2, 924, 633);
    }// </editor-fold>//GEN-END:initComponents

    private void txtProveedorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProveedorIDActionPerformed
        Proveedor proveedor = new Proveedor();
        Object o[][] = control.seekUniversal(proveedor.getVectorData(), "Proveedor", txtProveedorID.getText());
        if (o != null) {
            proveedor=new Proveedor(o);
            lblNombreProveedor.setText(proveedor.getNombre());
            lblDireccionProveedor.setText(proveedor.getDireccion());
            limite=proveedor.getLimite();
            a=true;
            txtChequeID.grabFocus();
        }
    }//GEN-LAST:event_txtProveedorIDActionPerformed

    private void validActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validActionPerformed
        if(!a){
            JOptionPane.showMessageDialog(rootPane,"Campo Codigo de Proveedor no esta validado","Error",JOptionPane.ERROR_MESSAGE);
            txtProveedorID.grabFocus();
        }
        else if(!d){
            JOptionPane.showMessageDialog(rootPane,"Campo No. de Cheque no esta validado","Error",JOptionPane.ERROR_MESSAGE);
            txtChequeID.grabFocus();
        }
        else{
            pagocab=new PagoCab(inter.String_Int(txtPagoID.getText()),inter.String_Int(txtProveedorID.getText()),inter.String_Int(lblBancoNombre.getName()),lblCuentaID.getText(),inter.String_Int(txtChequeID.getText()),txtFecha.getText(),"P");
            ins=true;
            txtCompraID.grabFocus();
        }
    }//GEN-LAST:event_validActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Limpiar_Campos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(!ins){
            JOptionPane.showMessageDialog(rootPane,"El encabezado de Pago no esta validado aun!!!","Error",JOptionPane.ERROR_MESSAGE);
            valid.grabFocus();
        }
        else if(modelo.getRowCount()==0){
            JOptionPane.showMessageDialog(rootPane, "No se han ingresado Ordenes de Compra en el detalle de Pago");
            txtCompraID.grabFocus();
        }
        else{
            int res=JOptionPane.showConfirmDialog(rootPane,"¿Desea GRABAR ESTA ORDEN?","PREGUNTA",JOptionPane.YES_NO_OPTION);
            if(res==JOptionPane.YES_OPTION){
                boolean y=control.insUniversal2(pagocab.getVectorData(), "PagoCab");
                if(y){
                    Cheque cheque = new Cheque();
                    Object o[][] = control.seekUniversal(cheque.getVectorData(), "Cheque", txtChequeID.getText());
                    if (o != null) {
                        cheque = new Cheque(o);
                        cheque.setEstado("P");
                        y = control.updUniversal2(cheque.getVectorData(),"Cheque",cheque.getChequeID()+"");
                    }
                }
                boolean x=false;
                for(PagoDet o:PagoDet){
                    x=control.insUniversal2(o.getVectorData(), "PagoDet");
                    if(!x){
                        break;
                    }
                    else{
                        CompraCab compracab = new CompraCab();
                        Object oo[][] = control.seekUniversal(compracab.getVectorData(), "CompraCab",o.getCompraID()+"");
                        if (oo != null) {
                            compracab = new CompraCab(oo);
                            compracab.setEstado("P");
                            control.updUniversal2(compracab.getVectorData(),"CompraCab",compracab.getCompraID()+"");
                        }
                    }
                }
                if((y) && (x)){
                    JOptionPane.showMessageDialog(rootPane, "OPERACION EFECTUADA CON EXITO");
                }
                totalBruto = 0;
                totalBruto = 0;
                txtCompraID.setText("");
                lblFacturaID.setText("");
                lblSubtotal.setText("");
                PagoDet.clear();
                for(int e=modelo.getRowCount()-1;e>-1;e--){
                    modelo.removeRow(e);
                }
                Limpiar_Campos();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtChequeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChequeIDActionPerformed
        Cheque cheque = new Cheque();
        Object o[][] = control.seekUniversal(cheque.getVectorData(), "Cheque", txtChequeID.getText());
        if (o != null) {
            cheque=new Cheque(o);
            if(cheque.getEstado().equals("P") || cheque.getEstado().equals("A")){
                JOptionPane.showMessageDialog(rootPane,"Cheque ya esta Pagado o Anulado","Mensaje",JOptionPane.ERROR_MESSAGE);
                txtChequeID.grabFocus();
            } else {
                lblNombreBeneficiario.setText(cheque.getBeneficiario());
                lblValor.setText(cheque.getValor() + "");
                Banco banco = new Banco();
                Object oo[][] = control.seekUniversal(banco.getVectorData(), "Banco", cheque.getBancoID() + "");
                if (oo != null) {
                    banco = new Banco(oo);
                    lblBancoNombre.setName(banco.getBanco_id() + "");
                    lblBancoNombre.setText(banco.getNombre_Banco());
                }
                Cuenta cuenta = new Cuenta();
                Object ooo[][] = control.seekUniversal(cuenta.getVectorData(), "Cuenta", "'" + cheque.getCuentaID() + "'");
                if (ooo != null) {
                    cuenta = new Cuenta(ooo);
                    lblCuentaID.setText(cuenta.getCuentaID());
                    lblCuentaNombre.setText(cuenta.getNombre());
                }
                d = true;
                valid.grabFocus();
            }
        }
    }//GEN-LAST:event_txtChequeIDActionPerformed

    private void txtCompraIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompraIDActionPerformed
        if (ins) {
            if (!txtCompraID.getText().isEmpty()) {
                CompraCab compracab = new CompraCab();
                Object o[][] = control.seekUniversal(compracab.getVectorData(), "CompraCab", txtCompraID.getText());
                if (o != null) {
                    compracab = new CompraCab(o);
                    if (compracab.getEstado().equals("P") || compracab.getEstado().equals("N")) {
                        JOptionPane.showMessageDialog(rootPane, "No se Puede Mostrar Esta Orden de Compra Pues ya Esta Pagada o Anulada", "Mensaje", JOptionPane.ERROR_MESSAGE);
                    }
                    else if (compracab.getProveedorID()!=inter.String_Int(txtProveedorID.getText())) {
                        JOptionPane.showMessageDialog(rootPane, "No se Puede Mostrar Esta Orden de Compra Pues son de proveedores Diferentes", "Mensaje", JOptionPane.ERROR_MESSAGE);
                    }                    
                    else {
                        lblFacturaID.setText(compracab.getFactura()+"");
                        totalBruto=0;
                        CompraDet compradet = new CompraDet();
                        Vector<Object[][]> kk = control.seekUniversalVector(compradet.getVectorData(), "CompraDet", txtCompraID.getText());
                        if (!kk.isEmpty()) {
                            for (Object ll[][] : kk) {
                                compradet = new CompraDet(ll);
                                int cantidad=0;
                                float precio=0,isv=0;
                                cantidad=compradet.getCantidad();
                                precio=compradet.getPrecio();
                                if(compradet.getISV()==1){
                                    isv=(float) (cantidad*precio*0.12);
                                }
                                totalBruto=totalBruto+(cantidad*precio)+isv;
                            }
                            lblSubtotal.setText(totalBruto+"");
                        }
                    }
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane,"El Campo No. de Compra esta Vacio","Error",JOptionPane.ERROR_MESSAGE);
                txtCompraID.grabFocus();
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"El encabezado del Pago no esta validado aun!!!","Error",JOptionPane.ERROR_MESSAGE);
            valid.grabFocus();
        }
    }//GEN-LAST:event_txtCompraIDActionPerformed

    private void btnQuitarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarLineaActionPerformed
        int x=-1;
        x=Tabla.getSelectedRow();
        if(x<0){
            JOptionPane.showMessageDialog(rootPane, "No se puede debes de seleccionar una linea de la tabla");
        }
        else{
            total=total- Float.valueOf(modelo.getValueAt(x, 2).toString());
            lblTotal.setText(total+"");
            PagoDet.remove(x);
            modelo.removeRow(x);
            txtCompraID.setText("");
            lblFacturaID.setText("");
            lblSubtotal.setText("");
            txtCompraID.grabFocus();
        }
    }//GEN-LAST:event_btnQuitarLineaActionPerformed

    private void btnAgregarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLineaActionPerformed
        if(txtCompraID.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "No se puede ingresar linea con campos vacios");
        }
        else{
            Vector rou = new Vector();
            rou.addElement(txtCompraID.getText());
            rou.addElement(lblFacturaID.getText());
            rou.addElement(lblSubtotal.getText());
            total = total + totalBruto;
            lblTotal.setText(total + "");
            pagodet = new PagoDet(pagocab.getPagoID(),inter.String_Int(txtCompraID.getText()), totalBruto);
            PagoDet.addElement(pagodet);
            modelo.addRow(rou);
            totalBruto = 0;
            txtCompraID.setText("");
            lblFacturaID.setText("");
            lblSubtotal.setText("");
            txtCompraID.grabFocus();
        }
    }//GEN-LAST:event_btnAgregarLineaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnAgregarLinea;
    private javax.swing.JButton btnQuitarLinea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBancoNombre;
    private javax.swing.JLabel lblCuentaID;
    private javax.swing.JLabel lblCuentaNombre;
    private javax.swing.JLabel lblDireccionProveedor;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFacturaID;
    private javax.swing.JLabel lblNombreBeneficiario;
    private javax.swing.JLabel lblNombreProveedor;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtChequeID;
    private javax.swing.JTextField txtCompraID;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtPagoID;
    private javax.swing.JTextField txtProveedorID;
    private javax.swing.JButton valid;
    // End of variables declaration//GEN-END:variables
}
