package Vistax;
import Controller.ControlUniversal;
import Modelos.Empresa;
import Modelos.Puesto;
import Modelos.Socio;
import Utilerias.interfacex;
import java.text.DateFormat;
import java.text.FieldPosition;
import java.text.ParsePosition;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author root4142
 */
public class frmSocio extends javax.swing.JInternalFrame {
    private interfacex inter=new interfacex();
    private Vector<JTextField> txtCampos=new Vector<>();
    private Date date;
    private boolean ins=true,b=false,c=false;
    private ControlUniversal control;
    private Socio socio;
    private String state="";
    /**
     * Creates new form frmSocio
     */
    public frmSocio(ControlUniversal cont) {
        initComponents();
        control=cont;
        txtCampos.add(txtSocioID);
        txtCampos.add(txtCodigo);
        txtCampos.add(txtNombre);
        txtCampos.add(txtDireccion);
        txtCampos.add(txtTelefono);
        txtCampos.add(txtEmpresaID);
        txtCampos.add(txtSueldo);
        txtCampos.add(txtAhorro);
        txtCampos.add(txtPuestoID);
        socio=new Socio();
        date=new Date();
        date=control.getFechaSistemaSql();
        cboFecha.setDate(date);
        int auto = control.autoUniversal2("Socio","SocioID");
        txtSocioID.setText(String.valueOf(auto));
        txtCodigo.grabFocus();
    }
    private void Limpiar_Campos(){
        date=new Date();
        date=control.getFechaSistemaSql();
        cboFecha.setDate(date);
        for (JTextField o : txtCampos) {
            o.setText("");
        }
        cboCivil.setSelectedIndex(0);
        rdMasculino.setSelected(true);
        lblNombreEmpresa.setText("");
        lblNombrePuesto.setText("");
        ins=true;
        b=false;c=false;
        int auto = control.autoUniversal2("Socio","SocioID");
        txtSocioID.setText(String.valueOf(auto));
        txtCodigo.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        txtSocioID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rdFemenino = new javax.swing.JRadioButton();
        rdMasculino = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        cboCivil = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtAhorro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cboFecha = new com.toedter.calendar.JDateChooser();
        txtEmpresaID = new javax.swing.JTextField();
        lblNombreEmpresa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPuestoID = new javax.swing.JTextField();
        lblNombrePuesto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setTitle("Formulario de Socios.");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistax/Iconos/icon.jpeg"))); // NOI18N
        setName("frmSocio"); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("ID Socio :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        txtSocioID.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        txtSocioID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSocioID.setEnabled(false);
        txtSocioID.setName("SocioID"); // NOI18N
        txtSocioID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSocioIDKeyPressed(evt);
            }
        });
        getContentPane().add(txtSocioID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 80, -1));

        jLabel7.setText("Direccion :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        txtCodigo.setName("Codigo"); // NOI18N
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 200, -1));

        txtNombre.setName("Nombre"); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 300, -1));

        jLabel8.setText("Codigo :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel9.setText("Nombre :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        buttonGroup1.add(rdFemenino);
        rdFemenino.setText("Femenino");
        getContentPane().add(rdFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        buttonGroup1.add(rdMasculino);
        rdMasculino.setSelected(true);
        rdMasculino.setText("Masculino");
        getContentPane().add(rdMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel10.setText("Sexo :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        cboCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Soltero", "Casado", "Union Libre" }));
        getContentPane().add(cboCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 180, -1));

        jLabel11.setText("Estado Civil :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        txtDireccion.setName("Direccion"); // NOI18N
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 300, -1));

        jLabel12.setText("Fecha de Ingreso :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        txtAhorro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAhorro.setName("Ahorro"); // NOI18N
        getContentPane().add(txtAhorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 120, -1));

        jLabel13.setText("Telefono :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        cboFecha.setDateFormatString("MMMMM d, yyyy");
        getContentPane().add(cboFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 200, -1));

        txtEmpresaID.setBackground(java.awt.Color.white);
        txtEmpresaID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmpresaID.setName("EmpresaID"); // NOI18N
        txtEmpresaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpresaIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmpresaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 90, -1));

        lblNombreEmpresa.setBackground(java.awt.Color.white);
        lblNombreEmpresa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNombreEmpresa.setOpaque(true);
        getContentPane().add(lblNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 250, 30));

        jLabel3.setText("Ahorro :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        txtPuestoID.setBackground(java.awt.Color.white);
        txtPuestoID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPuestoID.setName("PuestoID"); // NOI18N
        txtPuestoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPuestoIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtPuestoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 90, -1));

        lblNombrePuesto.setBackground(java.awt.Color.white);
        lblNombrePuesto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNombrePuesto.setOpaque(true);
        getContentPane().add(lblNombrePuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 250, 30));

        jLabel4.setText("Codigo de Puesto :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLabel5.setText("Codigo de la Empresa :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel6.setText("Sueldo :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        txtTelefono.setName("Telefono"); // NOI18N
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 120, -1));

        txtSueldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSueldo.setName("Sueldo"); // NOI18N
        getContentPane().add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 120, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 80, -1));

        jButton2.setText("Recuperar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 110, -1));

        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 100, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-661)/2, (screenSize.height-553)/2, 661, 553);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSocioIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSocioIDKeyPressed
        if(txtSocioID.getText().length()>=20){
            evt.consume();
        }
    }//GEN-LAST:event_txtSocioIDKeyPressed

    private void txtEmpresaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpresaIDActionPerformed
        Empresa empresa = new Empresa();
        Object o[][] = control.seekUniversal(empresa.getVectorData(), "Empresa",txtEmpresaID.getText());
        if (o != null) {
            empresa = new Empresa(o);
            lblNombreEmpresa.setText(empresa.getNombre());
            b=true;
            txtSueldo.grabFocus();
        }
    }//GEN-LAST:event_txtEmpresaIDActionPerformed

    private void txtPuestoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuestoIDActionPerformed
        Puesto puesto = new Puesto();
        Object o[][] = control.seekUniversal(puesto.getVectorData(), "Puesto",txtPuestoID.getText());
        if (o != null) {
            puesto = new Puesto(o);
            lblNombrePuesto.setText(puesto.getNombre());
            c=true;
            jButton3.grabFocus();
        }
    }//GEN-LAST:event_txtPuestoIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int x=-1;
        try {
            x = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Ingrese Codigo del Deposito : ", "Ingrese", JOptionPane.INFORMATION_MESSAGE));
            socio = new Socio();
            Object o[][] = control.seekUniversal(socio.getVectorData(), "Socio", x+"");
            if (o != null) {
                socio = new Socio(o);
                txtSocioID.setText(socio.getSocioID()+"");
                txtCodigo.setText(socio.getCodigo());
                txtNombre.setText(socio.getNombre());
                if(socio.getSexo().equals("M")){
                    rdMasculino.setSelected(true);
                }
                else{
                    rdFemenino.setSelected(true);
                }
                if(socio.getCivil().equals("S")){
                    cboCivil.setSelectedIndex(0);
                }
                else if(socio.getCivil().equals("C")){
                    cboCivil.setSelectedIndex(1);
                }
                else if(socio.getCivil().equals("U")){
                    cboCivil.setSelectedIndex(2);
                }
                txtDireccion.setText(socio.getDireccion());
                txtTelefono.setText(socio.getTelefono());
                cboFecha.setDate(inter.String_Date(socio.getFechaIngreso()));
                txtEmpresaID.setText(socio.getEmpresaID()+"");
                txtEmpresaIDActionPerformed(evt);
                txtSueldo.setText(inter.FormatoSimple(socio.getSueldo()));
                txtAhorro.setText(inter.FormatoSimple(socio.getAhorro()));
                txtPuestoID.setText(socio.getPuestoID()+"");
                txtPuestoIDActionPerformed(evt);
                state=socio.getEstado();
                txtCodigo.grabFocus();
                ins = false;
                b = false;
                c = false;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"Debe de ingresar un ID de Socio Valido","Error",JOptionPane.ERROR_MESSAGE);
            Limpiar_Campos();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean a=false, bb=false;
        for(JTextField o:txtCampos){
            if(o.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane,"Campo "+o.getName()+" se encuentra Vacio","Error",JOptionPane.ERROR_MESSAGE);
                o.grabFocus();
                a=false;
                break;
            }
            else{
                a=true;
            }
        }
        if (a) {
            if (!b) {
                JOptionPane.showMessageDialog(rootPane, "Campo Empresa ID no esta Validado", "Error", JOptionPane.ERROR_MESSAGE);
                bb = false;
                txtEmpresaID.grabFocus();
            }
            else if (!c) {
                JOptionPane.showMessageDialog(rootPane, "Campo Puesto ID no esta Validado", "Error", JOptionPane.ERROR_MESSAGE);
                bb = false;
                txtPuestoID.grabFocus();
            }
            else if(ins && control.seekUniversal("Socio", "Codigo","'"+txtCodigo.getText().toUpperCase().trim()+"'" )){
                JOptionPane.showMessageDialog(rootPane, "Codigo de Socio ya existe", "Error", JOptionPane.ERROR_MESSAGE);
                bb = false;
                txtCodigo.grabFocus();
            }
            else if((inter.String_Float(txtAhorro.getText())>0.35 || inter.String_Float(txtAhorro.getText())<0)){
                JOptionPane.showMessageDialog(rootPane, "Campo de ahorro debe de ser menor de 0.35 y mayor de 0", "Error", JOptionPane.ERROR_MESSAGE);
                bb = false;
                txtAhorro.grabFocus();
            }
            else {
                bb = true;
            }
            
            if (bb) {
                String xx = "", yy = "",zz="";
                Date d=cboFecha.getDate();
                xx=inter.Date_String(d);
                if (cboCivil.getSelectedIndex() == 0) {
                    yy = "S";
                } else if (cboCivil.getSelectedIndex() == 1) {
                    yy = "C";
                } else if (cboCivil.getSelectedIndex() == 2) {
                    yy = "U";
                }
                if(rdMasculino.isSelected()){
                    zz="M";
                }
                else{
                    zz="F";
                }
                socio = new Socio(inter.String_Int(txtSocioID.getText()), txtCodigo.getText(),txtNombre.getText().toUpperCase(),zz,yy,txtDireccion.getText().toUpperCase(),txtTelefono.getText(),xx,"1",inter.String_Int(txtEmpresaID.getText()),inter.String_Float(txtSueldo.getText()),inter.String_Float(txtAhorro.getText()),inter.String_Int(txtPuestoID.getText()));
                if (ins) {
                    control.insUniversal(socio.getVectorData(), "Socio");
                } else {
                    socio.setEstado(state);
                    control.updUniversal(socio.getVectorData(), "Socio", txtSocioID.getText());
                }
                Limpiar_Campos();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        if(txtCodigo.getText().length()>=20){
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        if(txtNombre.getText().length()>=50){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        if(txtDireccion.getText().length()>=50){
            evt.consume();
        }
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        if(txtTelefono.getText().length()>=20){
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboCivil;
    private com.toedter.calendar.JDateChooser cboFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblNombreEmpresa;
    private javax.swing.JLabel lblNombrePuesto;
    private javax.swing.JRadioButton rdFemenino;
    private javax.swing.JRadioButton rdMasculino;
    private javax.swing.JTextField txtAhorro;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmpresaID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPuestoID;
    private javax.swing.JTextField txtSocioID;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
