package Vistax;
import Controller.ControlUniversal;
import Modelos.Empresa;
import Modelos.Existencia;
import Modelos.Tienda;
import Modelos.TiendaEmpresa;
import Utilerias.interfacex;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author root4142
 */
public class frmTiendaEmpresa extends javax.swing.JInternalFrame {
    private interfacex inter=new interfacex();
    private Vector<JTextField> txtCampos=new Vector<>();
    private boolean aa=false,bb=false;
    private ControlUniversal control;
    private Empresa empresa;
    private Tienda tienda;
    private Existencia existencia;
    
    public frmTiendaEmpresa(ControlUniversal cont) {
        initComponents();
        control=cont;
        txtCampos.add(txtTiendaID);
        txtCampos.add(txtEmpresaID);
        txtTiendaID.grabFocus();
    }
    private void Limpiar_Campos(){
        for (JTextField o : txtCampos) {
            o.setText("");
        }
        lblNombreEmpresa.setText("");
        lblNombreTienda.setText("");
        aa=false;bb=false;
        txtTiendaID.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtTiendaID = new javax.swing.JTextField();
        lblNombreTienda = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmpresaID = new javax.swing.JTextField();
        lblNombreEmpresa = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Formulario de Asignacion de Tienda.");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistax/Iconos/icon.jpeg"))); // NOI18N
        setName("frmTiendaEmpresa"); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Codigo de la Tienda :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtTiendaID.setBackground(java.awt.Color.white);
        txtTiendaID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTiendaID.setName("TiendaID"); // NOI18N
        txtTiendaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiendaIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtTiendaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 90, -1));

        lblNombreTienda.setBackground(java.awt.Color.white);
        lblNombreTienda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNombreTienda.setOpaque(true);
        getContentPane().add(lblNombreTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 250, 30));

        jLabel3.setText("Codigo de la Empresa :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtEmpresaID.setBackground(java.awt.Color.white);
        txtEmpresaID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmpresaID.setName("EmpresaID"); // NOI18N
        txtEmpresaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpresaIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmpresaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 90, -1));

        lblNombreEmpresa.setBackground(java.awt.Color.white);
        lblNombreEmpresa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNombreEmpresa.setOpaque(true);
        getContentPane().add(lblNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 250, 30));

        jButton1.setText("Procesar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 120, -1));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 80, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-611)/2, (screenSize.height-250)/2, 611, 250);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTiendaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiendaIDActionPerformed
        tienda = new Tienda();
        Object o[][] = control.seekUniversal(tienda.getVectorData(), "Tienda",txtTiendaID.getText());
        if (o != null) {
            tienda = new Tienda(o);
            lblNombreTienda.setText(tienda.getNombre());
            aa=true;
            txtEmpresaID.grabFocus();
        }
    }//GEN-LAST:event_txtTiendaIDActionPerformed

    private void txtEmpresaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpresaIDActionPerformed
        empresa = new Empresa();
        Object o[][] = control.seekUniversal(empresa.getVectorData(), "Empresa",txtEmpresaID.getText());
        if (o != null) {
            empresa = new Empresa(o);
            lblNombreEmpresa.setText(empresa.getNombre());
            bb=true;
            jButton1.grabFocus();
        }
    }//GEN-LAST:event_txtEmpresaIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean a=false,b=false;
        for(JTextField o:txtCampos){
            if(o.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane,"Campo "+o.getName()+" se encuentra Vacio","Error",JOptionPane.ERROR_MESSAGE);
                o.grabFocus();
                a=false;
                break;
            }
            else{
                a=true;
            }
        }
        if (a) {
            if(!aa){
                JOptionPane.showMessageDialog(rootPane,"Campo Tienda no esta validado","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                txtTiendaID.grabFocus();
            }
            else if(!bb){
                JOptionPane.showMessageDialog(rootPane, "Campo Empresa no esta validado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                txtEmpresaID.grabFocus();
            } else {
                boolean z = control.seekUniversal("SELECT * FROM TiendaEmpresa WHERE TiendaID=" + txtTiendaID.getText() + " and EmpresaID=" + txtEmpresaID.getText() + ";");
                if (z) {
                    JOptionPane.showMessageDialog(rootPane, "Ya existe un registro con estos campos", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    TiendaEmpresa tiendaempresa = new TiendaEmpresa(inter.String_Int(txtTiendaID.getText()), inter.String_Int(txtEmpresaID.getText()));
                    control.insUniversal(tiendaempresa.getVectorData(), "TiendaEmpresa");
                }
                Limpiar_Campos();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNombreEmpresa;
    private javax.swing.JLabel lblNombreTienda;
    private javax.swing.JTextField txtEmpresaID;
    private javax.swing.JTextField txtTiendaID;
    // End of variables declaration//GEN-END:variables
}
