package Vistax;
import Controller.ControlUniversal;
import Modelos.Articulo;
import Modelos.Bodega;
import Modelos.Existencia;
import Modelos.Movimiento;
import Modelos.Tienda;
import Modelos.Traslado;
import Utilerias.interfacex;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author root4142
 */
public class frmTraslado extends javax.swing.JInternalFrame {
    private interfacex inter=new interfacex();
    private Vector<JTextField> txtCampos=new Vector<>();
    private Vector<JLabel> lblLabels=new Vector<>();
    private ControlUniversal control;
    private boolean a=false,b=false,c=false;
    
    
    public frmTraslado(ControlUniversal cont) {
        initComponents();
        control=cont;
        txtCampos.add(txtTrasladoID);
        txtCampos.add(txtFecha);
        txtCampos.add(txtBodegaID);
        txtCampos.add(txtTiendaID);
        txtCampos.add(txtArticuloID);
        txtCampos.add(txtCantidad);
        lblLabels.add(lblNombreBodega);
        lblLabels.add(lblNombreTienda);
        lblLabels.add(lblNombreArticulo);
        txtFecha.setText(control.getFechaSistema());
        int auto = control.autoUniversal2("Traslado","TrasladoID");
        txtTrasladoID.setText(String.valueOf(auto));
        txtBodegaID.grabFocus();
    }
    private void Limpiar_Campos(){
        for (JTextField o : txtCampos) {
            o.setText("");
        }
        for (JLabel o : lblLabels) {
            o.setText("");
        }
        a=false;b=false;c=false;
        txtFecha.setText(control.getFechaSistema());
        int auto = control.autoUniversal2("Traslado","TrasladoID");
        txtTrasladoID.setText(String.valueOf(auto));
        txtBodegaID.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTrasladoID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtBodegaID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNombreBodega = new javax.swing.JLabel();
        txtTiendaID = new javax.swing.JTextField();
        lblNombreTienda = new javax.swing.JLabel();
        txtArticuloID = new javax.swing.JTextField();
        lblNombreArticulo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Traslado de Articulos.");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistax/Iconos/icon.jpeg"))); // NOI18N
        setName("frmTraslado"); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTrasladoID.setBackground(java.awt.Color.white);
        txtTrasladoID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTrasladoID.setEnabled(false);
        txtTrasladoID.setName("TrasladoID"); // NOI18N
        getContentPane().add(txtTrasladoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("No. de Traslado :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setEnabled(false);
        txtFecha.setName("Fecha"); // NOI18N
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 150, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Año-Mes-Día");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        txtBodegaID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBodegaID.setName("BodegaID"); // NOI18N
        txtBodegaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBodegaIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtBodegaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Codigo de Bodega :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Codigo de Articulo :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        lblNombreBodega.setBackground(java.awt.Color.white);
        lblNombreBodega.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreBodega.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNombreBodega.setName("Estado"); // NOI18N
        lblNombreBodega.setOpaque(true);
        getContentPane().add(lblNombreBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 270, 30));

        txtTiendaID.setBackground(java.awt.Color.white);
        txtTiendaID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTiendaID.setName("Codigo_Tienda"); // NOI18N
        txtTiendaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiendaIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtTiendaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 90, -1));

        lblNombreTienda.setBackground(java.awt.Color.white);
        lblNombreTienda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNombreTienda.setOpaque(true);
        getContentPane().add(lblNombreTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 250, 30));

        txtArticuloID.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        txtArticuloID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtArticuloID.setName("Codigo_Articulo"); // NOI18N
        txtArticuloID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArticuloIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtArticuloID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 90, -1));

        lblNombreArticulo.setBackground(java.awt.Color.white);
        lblNombreArticulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNombreArticulo.setName(""); // NOI18N
        lblNombreArticulo.setOpaque(true);
        getContentPane().add(lblNombreArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 250, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Codigo de Tienda :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad.setName("Cantidad"); // NOI18N
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 100, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Cantidad :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jButton1.setText("PROCESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 110, 40));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 100, 40));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-629)/2, (screenSize.height-306)/2, 629, 306);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBodegaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBodegaIDActionPerformed
        Bodega bodega = new Bodega();
        Object o[][] = control.seekUniversal(bodega.getVectorData(), "Bodega", txtBodegaID.getText());
        if (o != null) {
            bodega=new Bodega(o);
            lblNombreBodega.setText(bodega.getNombre());
            a=true;
            txtTiendaID.grabFocus();
        }
    }//GEN-LAST:event_txtBodegaIDActionPerformed

    private void txtTiendaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiendaIDActionPerformed
        Tienda tienda = new Tienda();
        Object o[][] = control.seekUniversal(tienda.getVectorData(), "Tienda",txtTiendaID.getText());
        if (o != null) {
            tienda = new Tienda(o);
            lblNombreTienda.setText(tienda.getNombre());
            b=true;
            txtArticuloID.grabFocus();
        }
    }//GEN-LAST:event_txtTiendaIDActionPerformed

    private void txtArticuloIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArticuloIDActionPerformed
        Articulo articulo = new Articulo();
        Object o[][] = control.seekUniversal(articulo.getVectorData(), "Articulo",txtArticuloID.getText());
        if (o != null) {
            articulo = new Articulo(o);
            lblNombreArticulo.setText(articulo.getNombre());
            c=true;
            txtCantidad.grabFocus();
        }
    }//GEN-LAST:event_txtArticuloIDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean aa=false;
        for(JTextField o:txtCampos){
            if(o.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane,"Campo "+o.getName()+" se encuentra Vacio","Error",JOptionPane.ERROR_MESSAGE);
                o.grabFocus();
                aa=false;
                break;
            }
            else{
                aa=true;
            }
        }
        if (aa) {
            if (!a) {
                JOptionPane.showMessageDialog(rootPane, "Campo Codigo de Bodega no esta validado", "Error", JOptionPane.ERROR_MESSAGE);
                txtBodegaID.grabFocus();
            } else if (!b) {
                JOptionPane.showMessageDialog(rootPane, "Campo Codigo de la Tienda no esta validado", "Error", JOptionPane.ERROR_MESSAGE);
                txtTiendaID.grabFocus();
            } else if (!c) {
                JOptionPane.showMessageDialog(rootPane, "Campo Codigo del Articulo no esta validado", "Error", JOptionPane.ERROR_MESSAGE);
                txtArticuloID.grabFocus();
            } else {
                Traslado traslado = new Traslado(inter.String_Int(txtTrasladoID.getText()), inter.String_Int(txtBodegaID.getText()), inter.String_Int(txtTiendaID.getText()), txtFecha.getText(), "T", "E");
                boolean x = false, y = false, z = false;
                x = control.insUniversal2(traslado.getVectorData(), "Traslado");
                Movimiento movimiento = new Movimiento(traslado.getTrasladoID(), inter.String_Int(txtArticuloID.getText()), inter.String_Int(txtCantidad.getText()));
                y = control.insUniversal2(movimiento.getVectorData(), "Movimiento");
                Existencia existencia = new Existencia();
                Object o[][] = control.seekUniversal(existencia.getVectorData(), "Existencia", txtArticuloID.getText() + " and TiendaID=" + txtTiendaID.getText() + ";");
                if (o != null) {
                    existencia = new Existencia(o);
                    int k=existencia.getCantidad()+inter.String_Int(txtCantidad.getText());
                    existencia.setCantidad(k);
                    z = control.updUniversal2(existencia.getVectorData(), "Existencia", existencia.getArticuloID() + " and TiendaID=" + existencia.getTiendaID() + ";");
                }
                if (x && y && z) {
                    JOptionPane.showMessageDialog(rootPane, "MOVIMIENTO EFECTUADO CON EXITO");
                }
                Limpiar_Campos();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblNombreArticulo;
    private javax.swing.JLabel lblNombreBodega;
    private javax.swing.JLabel lblNombreTienda;
    private javax.swing.JTextField txtArticuloID;
    private javax.swing.JTextField txtBodegaID;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtTiendaID;
    private javax.swing.JTextField txtTrasladoID;
    // End of variables declaration//GEN-END:variables
}
